plugins {
    id "com.android.application"
}

android {
    namespace "com.cgwdev.wremail"
    compileSdk 35

    defaultConfig {
        applicationId "com.cgwdev.wremail"
        minSdk 26
        targetSdk 35
        versionCode 20
        versionName "2.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                    "META-INF/LICENSE.md",
                    "META-INF/NOTICE.md"
            ]
        }
    }
}

dependencies {
    implementation "com.sun.mail:android-mail:1.6.7"
    implementation "com.sun.mail:android-activation:1.6.7"
}
